# Generated by Django 5.2.3 on 2025-07-14 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('legajo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(help_text='Cargo o rol del personal autorizado', max_length=100)),
                ('activo', models.BooleanField(default=True, help_text='¿El personal está activo?')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=30, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Notas internas', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30)),
                ('chasis', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='AppCoder.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('sucursal', models.CharField(default='sin valor asignado', max_length=100)),
                ('nombre_empleado_entrego', models.CharField(default='sin valor asignado', max_length=100)),
                ('confirmacion_entregado', models.BooleanField(default=False)),
                ('accesorios_instalados', models.ManyToManyField(blank=True, related_name='ordenes_trabajo', to='AppCoder.accesorio')),
                ('instalador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCoder.operario')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='AppCoder.unidades')),
            ],
        ),
    ]
