# Generated by Django 5.2.3 on 2025-07-14 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='personal_autorizado',
            field=models.ForeignKey(blank=True, help_text='Personal autorizado responsable de la orden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_autorizadas', to='AppCoder.personalautorizado'),
        ),
    ]
