# Generated by Django 5.2.3 on 2025-07-13 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_unidades_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='AppCoder.unidades')),
            ],
        ),
    ]
