# Generated by Django 5.2.3 on 2025-07-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_ordendetrabajo_personal_autorizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='personal_autorizado',
        ),
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='accesorios_instalados',
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='accesorios_instalados',
            field=models.TextField(blank=True, help_text='Accesorios instalados (texto libre)'),
        ),
    ]
