# Generated by Django 5.2.3 on 2025-07-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_accesorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='accesorios_instalados',
            field=models.CharField(default='sin accesorios', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='fecha',
            field=models.DateField(),
        ),
    ]
