# Generated by Django 5.2.3 on 2025-07-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_ordendetrabajo_accesorios_instalados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
