# Generated by Django 5.2.3 on 2025-07-13 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_alter_ordendetrabajo_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidades',
            name='accesorios',
        ),
    ]
