# Generated by Django 5.2.3 on 2025-07-14 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_remove_unidades_accesorios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operario',
            old_name='instalador',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='operario',
            old_name='OrdenDeTrabajo',
            new_name='legajo',
        ),
        migrations.AddField(
            model_name='operario',
            name='nombre',
            field=models.CharField(default='SinNombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='instalador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppCoder.operario'),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='accesorios_instalados',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
