# Generated by Django 5.2.3 on 2025-07-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_rename_instalador_operario_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='confirmacion_entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='nombre_empleado_entrego',
            field=models.CharField(default='sin valor asignado', max_length=100),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='sucursal',
            field=models.CharField(default='sin valor asignado', max_length=100),
        ),
    ]
