# Generated by Django 5.2.3 on 2025-07-14 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_ordendetrabajo_confirmacion_entregado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregas',
        ),
    ]
